/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "data.pb-c.h"
void   msg__init
                     (Msg         *message)
{
  static const Msg init_value = MSG__INIT;
  *message = init_value;
}
size_t msg__get_packed_size
                     (const Msg *message)
{
  assert(message->base.descriptor == &msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg__pack
                     (const Msg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg__pack_to_buffer
                     (const Msg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg *
       msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg *)
     protobuf_c_message_unpack (&msg__descriptor,
                                allocator, len, data);
}
void   msg__free_unpacked
                     (Msg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor msg__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Msg, type),
    &message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Msg, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Msg, data_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Msg, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg__field_indices_by_name[] = {
  3,   /* field[3] = data */
  2,   /* field[2] = data_type */
  1,   /* field[1] = seq */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg",
  "Msg",
  "Msg",
  "",
  sizeof(Msg),
  4,
  msg__field_descriptors,
  msg__field_indices_by_name,
  1,  msg__number_ranges,
  (ProtobufCMessageInit) msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_type__enum_values_by_number[2] =
{
  { "MSG_REQ", "MESSAGE_TYPE__MSG_REQ", 0 },
  { "MSG_REP", "MESSAGE_TYPE__MSG_REP", 1 },
};
static const ProtobufCIntRange message_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex message_type__enum_values_by_name[2] =
{
  { "MSG_REP", 1 },
  { "MSG_REQ", 0 },
};
const ProtobufCEnumDescriptor message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageType",
  "MessageType",
  "MessageType",
  "",
  2,
  message_type__enum_values_by_number,
  2,
  message_type__enum_values_by_name,
  1,
  message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
